# Generated by Django 2.0.7 on 2018-07-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180709_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
